const mongoose = require('mongoose');
require('dotenv').config();

const Destination = require('./models/Destination');
const Package = require('./models/Package');
const Testimonial = require('./models/Testimonial');
const AdminUser = require('./models/AdminUser');

const destinations = [
  // ===================== DOMESTIC (India) =====================
  {
    name: 'Kerala',
    slug: 'kerala',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Premium',
    tagline: 'God\'s Own Country',
    description: 'Lush green backwaters, pristine beaches, aromatic spice plantations, and serene hill stations make Kerala a paradise on earth. Experience houseboat cruises through palm-fringed canals and Ayurvedic wellness retreats.',
    type: 'Nature',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1LbVlKYjedrexvv4vFLE_YRFVhf22_e_7GES-iFS2oliAm1-vxo86vr0aDs_2334rw0QnygORt9R-pjkT0ETejS5oUoVx-SdX0lqjrxvye4A8zJ2BS_TpOXkb7T-AlgegN4tOJz2ZbSE3YVxJJ6TM-wvJjbg8tnNpmq7gq5UY8CM193a_5gJcI-VnJzf75MKtkxgdsLQ-U66vGg_wPbOjcvFnx12zAVDTR6AQeSjQu4vNSe7rnx-dSUnczYFOKmwXjAsA_a5QKq4P',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDCh4g2x_nB5uyF5SzkCeWGnOhwQOuHwHWtnOdftn1snyU1Tw9bG_ykdfo_AwEKr4yo7O2p872AONY_HX_HP2oUoR2xsoo6V6_8wA62SVCV1N2QBBzBQNf6NNzfyjE0x9vWsgUV7K72X3g_yZmCDuuk3ilPvRpxr1xXMJTb0r1YGvDrR6J2Qzpzw3cla-iTn0PoJ47l2l3btjXIQJlK2fPGo57Qe-AlLx8-xN5fJtKlmSi057aNGiUpKtPXfA4RZYQUsxcmkzeVudP5',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDXT3aZU5ML7k2d3eOpEIJI5mNG09PFONIjFxZzQuIz0nm5LWWMfrDo_j-EHDR7weQyG5lIFoEWEWtskGos6mbBfZtYXewVXM4acD6sNN5kENRdR1JSo5FvB453BLzo3OcXqCaUwjdiZo3RedT8Tcx8mSi_rNQ2W6wFCzffFZq8YnScepJGZr6zsFOJvym1w4jfsUNJW5gIA5djP_Bn0jWlV-LS5Cm80IrpqThCUoxYxyrp-lB9MS5xaHflT-Uroo6Y0mKbAbDsZ96L',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCSP0w6aRchjavAFAO3QDjs4srq5jVmxtA__jmuTAT7v2-fZhQlUpFvqisQPBCgEIw3Uc8okQhFjemh7MIjb_eJMGXRQNcsIyEhaVNiqjaHE5B4iowWZHicAJvIfoutdvS4rblrvHauA5JK2yPFwCUMZBPmP-aIkf_H6iaZMeHMen2BXJt1lZZuAKMbWxbEkF5-lIziAHX8AQtSbmLeij8nR8wG4R0FFSUq-LaFfj0vIeTxlfN3vIYYe76TOva4z0OiGnhMnl2Jfsxq',
    ],
    seasons: ['Winter', 'Autumn'],
    isFeatured: true,
  },
  {
    name: 'Goa',
    slug: 'goa',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Value',
    tagline: 'Sun, Sand & Serenity',
    description: 'India\'s favourite beach paradise blending Portuguese heritage with vibrant nightlife. Golden beaches, historic churches, spice plantations, and world-class seafood make Goa a destination for every mood.',
    type: 'Beach',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUUfCqgJ9Gbeyb42FOx7CdP978XZRHfyL8E0m5xpMYFLeOnAcuKhdXz5X-QYt41OeYf5ZTJexqqtSkCn770mDAFMOJt-HX2k4hkcA0qPFoLe80bOMfBz9c1RSFDQBAIat1VHsjDRzYhYosw008ZyhohnTgPA3QgnfiNBaE8g9tD04GUlIj4szjCv271iaYQG86jJ4_HWLXljKLNANNHHuLaJDx2FFmLM5Y5kOiad2U65YQD35dRmP6EYe5_2xaEt5h9Mv2sa_yNf2z',
    galleryImages: [],
    seasons: ['Winter', 'Autumn'],
    isFeatured: true,
  },
  {
    name: 'Himachal Pradesh',
    slug: 'himachal-pradesh',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Premium',
    tagline: 'Where Mountains Whisper',
    description: 'Snow-capped peaks, lush valleys, ancient temples, and adventure trails define Himachal Pradesh. From the colonial charm of Shimla to the spiritual serenity of Dharamshala, every corner tells a story.',
    type: 'Mountain',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAN0bl2w6UanVhpueRMK6iMr1IBW_Yeq2aQ2-EBatc9bvWf355qkKqRb8uHak6-U3-ClraHaNgBGWPSYx1qmtu_KoMCoPbyqDEVtjR3ITCm9XEp4fjbKGgxY53PwsEriTIijnb9ZSDYt7tqinwuHcptj-m9HgJJNpbzezDeE07XHoHoVZkx5UvnJkyloiAEuot1o2kVQnSfQRn6RjKZ-ZJ99jXwWhabJjDhM2neFD23046AOsHbIsweOXED8Qoxe2QlrHS0v3-eaFEy',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDnM80F7IVRXt0kROm2JTsj9g6IPz8BLtNmb-x621jvR3aNEKsKj5rNfU7zBD7g2b5Onh_YlW4N1HRLOBDNPpFAhTZi4WkzmUuULSSE89AwfSzMygCKzHw91YrW2eZAg82cvwA_wzt7Ewu9dYjc8Ymjc6TGHLQgXeZhaRtxTXE9ZL6mxmpwI-9jqnc0I3J2OnOnBHxYxAnff6cPMe8z_U52neH7vu8Ay5SBkRrVOkEsuqmu4_4c0vVM9ubi7eJcouJnnE8xw_MR-mJB',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD9lJaZN3Ev56ZLJTStGfb5AMkhnSA4NEFdKDqrZxbH9yPaQXh2GhfSXjZOpeV7RsMZ4Kgx0ofTF2eZwsrt9xAP3DVNRz_DKK_T3oaPMxBXgwIkfteUTuZ7qD123gn0OEMGnIL3Nos4g_t64Ja_v3kIV8TVmKXBe5otG2MrBU9Wktm6NVfpPo3F8fkCSJwVObfqM1OsbVOtsAvMvMrLMbRL7A94_V-cAwjKcDCxCwmXPzjGqv5NzD8qag76R4I6GeuECf3jmjxvwoSJ',
    ],
    seasons: ['Summer', 'Winter'],
    isFeatured: true,
  },
  {
    name: 'Andaman and Nicobar Islands',
    slug: 'andaman-and-nicobar-islands',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Luxury',
    tagline: 'Emerald Isles of India',
    description: 'Crystal-clear turquoise waters, pristine coral reefs, lush tropical forests, and a rich colonial history. The Andaman Islands offer world-class diving, secluded beaches, and unforgettable sunsets over the Bay of Bengal.',
    type: 'Island',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgU2JZLkDHJxrrhKi9py-SiyrOo27ZtVGYXzR0JYUopr1E3Ibpv3_qvlpYkUNdLstKmH2IXqhRuuAhW9ZjaHHy0g-34t4H_pup4Iq5F6CNTEiWFcc5vV7HUn3H7kNOgXbgrR59yu2uxBzLxD3SPXZzut2M2nGscaAKMUh-1DNZDEtyD3m12hauvZbVouA236xoMs4k2ItQykHouC7TYPPKh01MSI80ZxSnZle2ch1smW041LBFAd9-RTmn3tCXvsvupBK1rzJXTKeI',
    galleryImages: [],
    seasons: ['Winter', 'Summer'],
    isFeatured: true,
  },
  {
    name: 'Rajasthan',
    slug: 'rajasthan',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Premium',
    tagline: 'Land of Kings',
    description: 'Experience the grandeur of Indian royalty through majestic palaces, imposing desert forts, vibrant bazaars, and the golden sands of the Thar Desert. Rajasthan is a living canvas of color and culture.',
    type: 'Cultural',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUD45bMtlYj3wamllJkxC1g1fATuM2HB5i8iRQ3Q615ywyjjwueCJIiB3jbmczY55KSc8wDPkVms-f0534L5eH1KnLAJWwqLrphsbuZQWyNlm8t6DpIOt6uykunN4HZpLG1p79lARv5bIJYI85bnI6AgtBXGUVJlvsvaNfrSZta3jZN7Oht1h-u_UJ9AyoQPpNepbui4bA-KltK348ejHE5rfVaXvcqruWehmWHAAq-vF4Nzcd0PKwENo0vGtHSJQQC31nQScZeQFi',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDCh4g2x_nB5uyF5SzkCeWGnOhwQOuHwHWtnOdftn1snyU1Tw9bG_ykdfo_AwEKr4yo7O2p872AONY_HX_HP2oUoR2xsoo6V6_8wA62SVCV1N2QBBzBQNf6NNzfyjE0x9vWsgUV7K72X3g_yZmCDuuk3ilPvRpxr1xXMJTb0r1YGvDrR6J2Qzpzw3cla-iTn0PoJ47l2l3btjXIQJlK2fPGo57Qe-AlLx8-xN5fJtKlmSi057aNGiUpKtPXfA4RZYQUsxcmkzeVudP5',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCJnHlJIo1NLva6qGeqrSyS7sBqzcuqriz6L_AuqXUB9ihkW_ZPBIJny3NlK2UVoMB4hiqh59NLnTvkEixT2CObrWdHWzrS5AL8T6yDnwHjd7BBbozJd69xV7428bFngFWGijv1rnWz6UF4muZ3w2P4PKMQgDv2HC2kVoRSvwmkyYwGwgwlhCBSnREMNJ7LHkTEMKQ42Xk8bZx8fjFD_xlqnSptPHGsbUH4iKaaLTfcl1adFwwmbXJOsB-ki2YqZ9ehn2nBebfzXFD4',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDXT3aZU5ML7k2d3eOpEIJI5mNG09PFONIjFxZzQuIz0nm5LWWMfrDo_j-EHDR7weQyG5lIFoEWEWtskGos6mbBfZtYXewVXM4acD6sNN5kENRdR1JSo5FvB453BLzo3OcXqCaUwjdiZo3RedT8Tcx8mSi_rNQ2W6wFCzffFZq8YnScepJGZr6zsFOJvym1w4jfsUNJW5gIA5djP_Bn0jWlV-LS5Cm80IrpqThCUoxYxyrp-lB9MS5xaHflT-Uroo6Y0mKbAbDsZ96L',
    ],
    seasons: ['Winter', 'Autumn'],
    isFeatured: true,
  },
  {
    name: 'Uttarakhand',
    slug: 'uttarakhand',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Value',
    tagline: 'Land of the Gods',
    description: 'From the spiritual banks of Rishikesh and Haridwar to the breathtaking meadows of Valley of Flowers, Uttarakhand is where adventure meets divine serenity amidst the mighty Himalayas.',
    type: 'Adventure',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBykTSOcudF4tEZ5OkFbQShq3658sTZuytCERzqtKlOUwUr53cImMOU3IuCPpCZVFOFtBnq5vtMyNh2_v5vh1Lfzs8BFfR7mTY1hYobHbZnX7AOyZWyvANCKgfIVXGGk1JEaVKLz5l2ow1OCdlyqYJfyOuF2rq-hDvEOApjo5nLFeQL0vxofT4tCvLsBrpAjyqUyPFDcqTRLpOoqv8qHaop1VsYPKzgqZyLvYVb0_miplusG19f80ANZauJMrn81ZavkMi92dkurLz5',
    galleryImages: [],
    seasons: ['Summer', 'Autumn'],
    isFeatured: false,
  },
  {
    name: 'Jammu and Kashmir',
    slug: 'jammu-and-kashmir',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Luxury',
    tagline: 'Paradise on Earth',
    description: 'Snow-dusted peaks reflecting in the mirror-still Dal Lake, vibrant Mughal gardens, and the intoxicating aroma of saffron fields. Kashmir is poetry written by nature herself.',
    type: 'Nature',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWS1kF1W3NmmdC0E1TJZH7mz3wZQN4pazlT5zjr0Q_JLl9SgL9xqgbhHru2lyLke453Xiqythv7j1hMDnvXszY4DCT2DwDUCT9N6TxBCNzRV6TGo33fmAPRAfl_F7hKsD-4VQmDtrxdkNPMg7syezuqULWaF8RgSznadcctkToLFUvlj8J97y8aDdHT3UGXayjLQu99qy9pT3-YYDaZ0IpXVxX_a1ccpPdBw7ayyuPqV5AqTvFqFFLEUv_akoeb0B_jfRUFzPpeuWg',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA4xbGOaKsxjN97ELeC0kt7iSmW9inE_a5IcBKwFzkMiEAJbE1IxAyELKMXX0HiwtgG32dH1ehGtSmUXfUhiy8T5jn55qf4bFJnr_n-jbXBkKpyV0X6_5BRGtCtmW7-EYcem-7ahJBhuM7kB83FlVVD9dp9qCtCNY5mD0_UCDIUQMaLGEXsl88NDb3E3Vde6EwYzMuQZOyqbCDoayNQRQWFty2SqtQyVkO7n6Z4HGzlzu9Cu7bR-3QD7Z4ht9BU-DXxfazQuYsOY3Sm',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBeVMNubeyWnDFlQFw0ihqcpv-mNwURZAOPL_PhMTa2HY1Y6pOa3vTHD_QuKUPetVFX8-XHbU8MNBJtey5DWI-uFxt2OSENYQNuspDoTX66QQiFiYOlY9wjsUcDAJwPozdleoE5pcr_hfUyS2SpSyE_WAd5B11j_vM_SoqYsP62CUav3_ck2HHUjQ54NGDAPV64H_jFtjjUITDrYv2Ez366C7Bw9WsHy-KCWQF56A7qirESR6MJ9LQsslMSECaTSgVQJZbifN7GZMlX',
    ],
    seasons: ['Summer', 'Autumn', 'Winter'],
    isFeatured: true,
  },
  {
    name: 'Uttar Pradesh',
    slug: 'uttar-pradesh',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Value',
    tagline: 'Heritage Beyond Time',
    description: 'Home to the iconic Taj Mahal, the spiritual ghats of Varanasi, and the ancient city of Lucknow. Uttar Pradesh is a living museum of India\'s most celebrated history and culture.',
    type: 'Heritage',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBNclNECedoflhi0cSxAK6iHlR7hRNLu-FP9Ds_Yo4LWCG5G3dy-XdbgfPsiPwmUJ9-MLn2ryHQv-nFMBRHMZcua6P0K3qVSO8hMhJyqOb9LivFh88WiJm0GO0novTC_QAvasT7k-L7wHuVvY-DQePmzJQZDNkgCTwACGRrPGgD6ZcOWhGoFrRUflw56-ktIXWdwGeJi4JpuPf4kKECa0UGB5bDNfcinhONm45HXpIjTBekK7aA_4Lb5y7pCRGojJtfgg-e11V53d1r',
    galleryImages: [],
    seasons: ['Winter', 'Autumn'],
    isFeatured: false,
  },
  {
    name: 'Gujarat',
    slug: 'gujarat',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Value',
    tagline: 'The Land of Legends',
    description: 'From the white salt desert of the Rann of Kutch to the sacred temple of Somnath, the lions of Gir, and the vibrant textile heritage — Gujarat is a treasure trove of surprises.',
    type: 'Cultural',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEEw_PPBqq94Smrm-zivW5LhkxtBdn-8Ivdd11jQOAZoFUvFkiiXK3m9wFSBFF3iiY27l08X_Sk7BvhOwZJdgwg1rRy7ankh1jJKrm-UHnORGrkJ3EC7JvCXH54S4fv8CQIyEoGPmS8ybQfWo1VmzoGCKABrlEVLQoKJwQbhMyTROYIXL8hHwJUEYf4qKxQ-ExVWeAdwgwCaGIv90sQJvk5maxhm_lerTmOl0N1vJTaG-qbdj4J1mgVfpEhbrFXhG1l1CV61jsWEq_',
    galleryImages: [],
    seasons: ['Winter', 'Autumn'],
    isFeatured: false,
  },
  {
    name: 'Lakshadweep',
    slug: 'lakshadweep',
    country: 'India',
    continent: 'Asia',
    category: 'Domestic',
    tier: 'Luxury',
    tagline: 'India\'s Hidden Tropical Paradise',
    description: 'A breathtaking archipelago of 36 coral islands in the Arabian Sea. Pristine lagoons, vibrant coral reefs, and untouched white-sand beaches make Lakshadweep India\'s best-kept secret.',
    type: 'Island',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5_nFiPFgg7uq1YpENSaveTpDPCTwOtYsC8wAhrS1cqCYGWuNzvsbo4m2piPD5QFiZcFaNPx16Sd-gMQq83kMlnEt5AaP_6knEQN9haPtbGM-3yrimZTMw8Po9lCPQXHd2BCs0a2ue-SFbwK_F01xBPpTszF2trrBfJ7ofMoLOickkK-8JyO40SkFs17bVrvbV1AcPQ_3KLw8aAPltet5VIQHcaF4FgwzjuunySZlgi1iVz2nA-swykz_6BIqBmE2fz0_FTLDMLOs1',
    galleryImages: [],
    seasons: ['Winter', 'Summer'],
    isFeatured: false,
  },

  // ===================== INTERNATIONAL =====================
  {
    name: 'Indonesia',
    slug: 'indonesia',
    country: 'Indonesia',
    continent: 'Asia',
    category: 'International',
    tier: 'Premium',
    tagline: 'Islands of Wonder',
    description: 'From the spiritual rice terraces of Bali to the ancient temples of Yogyakarta and the komodo dragons of Flores — Indonesia is a sprawling archipelago of extraordinary natural beauty and culture.',
    type: 'Adventure',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHXBeHe4FJ6en28QVtjl52tU6d7r2I5YMBxwLPiCthycqSkI4nJBshj-vBDzpuYZPJJMGAEH3NNzL9bfkjCh2xdHJhEtWvqtp5INFexsoVSDoMmBQRHUP2I8wAX4RFVdcMIcLYyaAomIabsTGx8b_4WHRkIIz8epxh1pffFgYLZr8BBbJs7xZSFjS9giDG2CSxxP8yrPfJhJc3dNGGDWTD8W8KW58_bt2svwXyftzfKNLKy19kfzCsKWMoZCa2Bd5EubFZbvG5f6_B',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDISU6lJwFt3ggY7k_8H91ll0JdmgWKYefy0csvojSO2CF1MIyMT8eeoL4FwWNwJjsN5TvtFBGH6AUpvbGba2iSBep9H5sxvo9FlHpdff6B15s9tT1b0STdWXN5aMktDrZVbQm7jmZzGaJq2Xi1K84TJ1tWDJKb1pj5CKcluonNSWXVYkdzqwzoWotjbceZzC2AJnSOV0Bgk_67Dc0ybOl4jas6vNPrkMU_bMUr0vYjWAqQOSuOlSzAOxLe_Ez0af31pJWtsAqe6Fku',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD83hi7VRPw1oot6fg-QZxfJ_OfkuOD7wUjhvuIXUxe_EWRxnKlbtgd72-lBkkaXZfinEussmuFSSuex6gGsSocMLs3d6XvTiMHGehbEXyeYxlTZQc6i_rt027YYTwz07saFGn6w8hSzhIBlNcFwG8kT04-9HE0mvtGRaXzm0VHCYjkgOSs-0IVN5ow-YXa2Sp6eP_F5MZ9TKQlnJG9wZ79AVN-SV1z1BdZ9Vwds5R0GD_ut4926g8B0cphK7U23rJNG6ggUHAqzJAa',
    ],
    seasons: ['Summer', 'Autumn'],
    isFeatured: true,
  },
  {
    name: 'Thailand',
    slug: 'thailand',
    country: 'Thailand',
    continent: 'Asia',
    category: 'International',
    tier: 'Value',
    tagline: 'Land of Smiles',
    description: 'Ancient golden temples, floating markets, pristine tropical islands, and a street food scene that will redefine your palate. Thailand effortlessly blends tradition with tropical indulgence.',
    type: 'Cultural',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4xbGOaKsxjN97ELeC0kt7iSmW9inE_a5IcBKwFzkMiEAJbE1IxAyELKMXX0HiwtgG32dH1ehGtSmUXfUhiy8T5jn55qf4bFJnr_n-jbXBkKpyV0X6_5BRGtCtmW7-EYcem-7ahJBhuM7kB83FlVVD9dp9qCtCNY5mD0_UCDIUQMaLGEXsl88NDb3E3Vde6EwYzMuQZOyqbCDoayNQRQWFty2SqtQyVkO7n6Z4HGzlzu9Cu7bR-3QD7Z4ht9BU-DXxfazQuYsOY3Sm',
    galleryImages: [],
    seasons: ['Winter', 'Autumn'],
    isFeatured: true,
  },
  {
    name: 'Singapore',
    slug: 'singapore',
    country: 'Singapore',
    continent: 'Asia',
    category: 'International',
    tier: 'Luxury',
    tagline: 'The Lion City',
    description: 'A futuristic cityscape where Gardens by the Bay meets hawker centres, Marina Bay Sands gleams beside heritage shophouses, and world-class shopping blends with multicultural cuisine.',
    type: 'Urban',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBeVMNubeyWnDFlQFw0ihqcpv-mNwURZAOPL_PhMTa2HY1Y6pOa3vTHD_QuKUPetVFX8-XHbU8MNBJtey5DWI-uFxt2OSENYQNuspDoTX66QQiFiYOlY9wjsUcDAJwPozdleoE5pcr_hfUyS2SpSyE_WAd5B11j_vM_SoqYsP62CUav3_ck2HHUjQ54NGDAPV64H_jFtjjUITDrYv2Ez366C7Bw9WsHy-KCWQF56A7qirESR6MJ9LQsslMSECaTSgVQJZbifN7GZMlX',
    galleryImages: [],
    seasons: ['Summer', 'Winter'],
    isFeatured: false,
  },
  {
    name: 'Malaysia',
    slug: 'malaysia',
    country: 'Malaysia',
    continent: 'Asia',
    category: 'International',
    tier: 'Value',
    tagline: 'Truly Asia',
    description: 'Petronas Twin Towers, ancient rainforests of Borneo, stunning islands of Langkawi, and the bustling streets of Penang. Malaysia offers an incredible fusion of modernity and untouched nature.',
    type: 'Nature',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrvoxh0MxPnPiDgE5B52XG-Pie4-XbuwjKoWXmuFrmdMYxtCQ2pIIRL1u7RG4UadeTMdY02j_eHF-gYLpwuSKYibs8RvEfDdMkQoq6blKET3fqaU32Y0_5GUdrrWOtaQeKsMzG_rBu6zJpOKg5m293kCzo2sybyS-28JtjsZFxKF9ow8BKmSI1eu2maTMki6g1KaDZRxz88mLWp4ssvJ_Xh7fYsWXxLs-pZP4w267S9IlodkwZ5Lr8h_j3E3w4A7vcyggJI43WLV4K',
    galleryImages: [],
    seasons: ['Summer', 'Winter'],
    isFeatured: false,
  },
  {
    name: 'Maldives',
    slug: 'maldives',
    country: 'Maldives',
    continent: 'Asia',
    category: 'International',
    tier: 'Luxury',
    tagline: 'Heaven on Earth',
    description: 'Crystal clear turquoise lagoons, overwater bungalows, pristine white sand beaches, and the world\'s most vibrant coral reefs. The Maldives is the ultimate luxury island escape in the Indian Ocean.',
    type: 'Island',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhQKeAaOwLL4QET6WPo7YZ8jF0e2VsSzyLal3aM8Yin8dYJrJcHJ_H1uOa05mzSX_otZ8bjZ3Rv5Cpb1kv3iE8YKXoUudRc7m30Fj2E66ynWtX6IgXDMOblfHQuM903t3dn_8MalFDuu-GuZ4WYci8XsXdaeFNIjbxYdefMS0CWUZSBdX5hy5YqzdZ0E3iKaZIzbjD32QYoYOrUaG_mDcnMlBkcjVS1fTPX_KpcjqFPbklDPgHVIYW0vPbMgMPJHpSEzUXqb3pSm8P',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC1LbVlKYjedrexvv4vFLE_YRFVhf22_e_7GES-iFS2oliAm1-vxo86vr0aDs_2334rw0QnygORt9R-pjkT0ETejS5oUoVx-SdX0lqjrxvye4A8zJ2BS_TpOXkb7T-AlgegN4tOJz2ZbSE3YVxJJ6TM-wvJjbg8tnNpmq7gq5UY8CM193a_5gJcI-VnJzf75MKtkxgdsLQ-U66vGg_wPbOjcvFnx12zAVDTR6AQeSjQu4vNSe7rnx-dSUnczYFOKmwXjAsA_a5QKq4P',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDgU2JZLkDHJxrrhKi9py-SiyrOo27ZtVGYXzR0JYUopr1E3Ibpv3_qvlpYkUNdLstKmH2IXqhRuuAhW9ZjaHHy0g-34t4H_pup4Iq5F6CNTEiWFcc5vV7HUn3H7kNOgXbgrR59yu2uxBzLxD3SPXZzut2M2nGscaAKMUh-1DNZDEtyD3m12hauvZbVouA236xoMs4k2ItQykHouC7TYPPKh01MSI80ZxSnZle2ch1smW041LBFAd9-RTmn3tCXvsvupBK1rzJXTKeI',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCSP0w6aRchjavAFAO3QDjs4srq5jVmxtA__jmuTAT7v2-fZhQlUpFvqisQPBCgEIw3Uc8okQhFjemh7MIjb_eJMGXRQNcsIyEhaVNiqjaHE5B4iowWZHicAJvIfoutdvS4rblrvHauA5JK2yPFwCUMZBPmP-aIkf_H6iaZMeHMen2BXJt1lZZuAKMbWxbEkF5-lIziAHX8AQtSbmLeij8nR8wG4R0FFSUq-LaFfj0vIeTxlfN3vIYYe76TOva4z0OiGnhMnl2Jfsxq',
    ],
    seasons: ['Winter', 'Summer'],
    isFeatured: true,
  },
  {
    name: 'Dubai',
    slug: 'dubai',
    country: 'United Arab Emirates',
    continent: 'Asia',
    category: 'International',
    tier: 'Luxury',
    tagline: 'City of Gold',
    description: 'A dazzling fusion of desert heritage and futuristic ambition. The Burj Khalifa pierces the sky, luxury malls glitter, desert safaris thrill, and the Dubai Marina shimmers under city lights.',
    type: 'Urban',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD83hi7VRPw1oot6fg-QZxfJ_OfkuOD7wUjhvuIXUxe_EWRxnKlbtgd72-lBkkaXZfinEussmuFSSuex6gGsSocMLs3d6XvTiMHGehbEXyeYxlTZQc6i_rt027YYTwz07saFGn6w8hSzhIBlNcFwG8kT04-9HE0mvtGRaXzm0VHCYjkgOSs-0IVN5ow-YXa2Sp6eP_F5MZ9TKQlnJG9wZ79AVN-SV1z1BdZ9Vwds5R0GD_ut4926g8B0cphK7U23rJNG6ggUHAqzJAa',
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDrvoxh0MxPnPiDgE5B52XG-Pie4-XbuwjKoWXmuFrmdMYxtCQ2pIIRL1u7RG4UadeTMdY02j_eHF-gYLpwuSKYibs8RvEfDdMkQoq6blKET3fqaU32Y0_5GUdrrWOtaQeKsMzG_rBu6zJpOKg5m293kCzo2sybyS-28JtjsZFxKF9ow8BKmSI1eu2maTMki6g1KaDZRxz88mLWp4ssvJ_Xh7fYsWXxLs-pZP4w267S9IlodkwZ5Lr8h_j3E3w4A7vcyggJI43WLV4K',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCHXBeHe4FJ6en28QVtjl52tU6d7r2I5YMBxwLPiCthycqSkI4nJBshj-vBDzpuYZPJJMGAEH3NNzL9bfkjCh2xdHJhEtWvqtp5INFexsoVSDoMmBQRHUP2I8wAX4RFVdcMIcLYyaAomIabsTGx8b_4WHRkIIz8epxh1pffFgYLZr8BBbJs7xZSFjS9giDG2CSxxP8yrPfJhJc3dNGGDWTD8W8KW58_bt2svwXyftzfKNLKy19kfzCsKWMoZCa2Bd5EubFZbvG5f6_B',
    ],
    seasons: ['Winter', 'Autumn', 'Summer'],
    isFeatured: true,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      Destination.deleteMany({}),
      Package.deleteMany({}),
      Testimonial.deleteMany({}),
    ]);
    console.log('🗑️  Cleared existing data');

    // Create destinations
    const createdDestinations = await Destination.insertMany(destinations);
    console.log(`✅ Created ${createdDestinations.length} destinations`);

    // Build destination ID map
    const destMap = {};
    createdDestinations.forEach(d => { destMap[d.slug] = d._id; });

    // Create packages
    const packages = [
      // ====== DOMESTIC PACKAGES ======
      {
        name: 'Kerala Backwater Bliss',
        slug: 'kerala-backwater-bliss',
        destination: destMap['kerala'],
        location: 'Kerala, India',
        description: 'Cruise through the enchanting backwaters of Alleppey on a luxury houseboat, explore Munnar\'s tea gardens, and rejuvenate with traditional Ayurvedic therapies in this all-encompassing Kerala experience.',
        duration: '7D/6N',
        days: 7,
        nights: 6,
        priceRange: { min: 25000, max: 55000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1LbVlKYjedrexvv4vFLE_YRFVhf22_e_7GES-iFS2oliAm1-vxo86vr0aDs_2334rw0QnygORt9R-pjkT0ETejS5oUoVx-SdX0lqjrxvye4A8zJ2BS_TpOXkb7T-AlgegN4tOJz2ZbSE3YVxJJ6TM-wvJjbg8tnNpmq7gq5UY8CM193a_5gJcI-VnJzf75MKtkxgdsLQ-U66vGg_wPbOjcvFnx12zAVDTR6AQeSjQu4vNSe7rnx-dSUnczYFOKmwXjAsA_a5QKq4P',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDCh4g2x_nB5uyF5SzkCeWGnOhwQOuHwHWtnOdftn1snyU1Tw9bG_ykdfo_AwEKr4yo7O2p872AONY_HX_HP2oUoR2xsoo6V6_8wA62SVCV1N2QBBzBQNf6NNzfyjE0x9vWsgUV7K72X3g_yZmCDuuk3ilPvRpxr1xXMJTb0r1YGvDrR6J2Qzpzw3cla-iTn0PoJ47l2l3btjXIQJlK2fPGo57Qe-AlLx8-xN5fJtKlmSi057aNGiUpKtPXfA4RZYQUsxcmkzeVudP5',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDXT3aZU5ML7k2d3eOpEIJI5mNG09PFONIjFxZzQuIz0nm5LWWMfrDo_j-EHDR7weQyG5lIFoEWEWtskGos6mbBfZtYXewVXM4acD6sNN5kENRdR1JSo5FvB453BLzo3OcXqCaUwjdiZo3RedT8Tcx8mSi_rNQ2W6wFCzffFZq8YnScepJGZr6zsFOJvym1w4jfsUNJW5gIA5djP_Bn0jWlV-LS5Cm80IrpqThCUoxYxyrp-lB9MS5xaHflT-Uroo6Y0mKbAbDsZ96L',
        ],
        badge: 'Best Seller',
        tags: ['Backwaters', 'Ayurveda', 'Houseboat', 'Tea Gardens', 'Nature'],
        highlights: [
          { icon: 'sailing', title: 'Houseboat Cruise', description: 'Overnight luxury houseboat cruise through Alleppey\'s palm-fringed backwaters.' },
          { icon: 'spa', title: 'Ayurvedic Retreat', description: 'Traditional Kerala Ayurvedic spa treatments and wellness therapy sessions.' },
          { icon: 'landscape', title: 'Tea Plantations', description: 'Guided tour of Munnar\'s sprawling emerald tea estates with tastings.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Kochi', description: 'Welcome at Cochin International Airport. Transfer to heritage hotel in Fort Kochi. Evening Chinese fishing nets walk and sunset.', tags: ['Transfer', 'Heritage Walk'] },
          { day: 2, title: 'Kochi to Munnar', description: 'Scenic drive through spice plantations to Munnar. Visit Eravikulam National Park and tea museum.', tags: ['Scenic Drive', 'Wildlife'] },
          { day: 3, title: 'Munnar Exploration', description: 'Full day exploring Mattupetty Dam, Echo Point, and tea garden walks. Evening bonfire at resort.', tags: ['Nature', 'Photography'] },
          { day: 4, title: 'Munnar to Thekkady', description: 'Drive to Periyar Wildlife Sanctuary. Afternoon spice plantation tour. Evening Kathakali dance show.', tags: ['Wildlife', 'Culture'] },
          { day: 5, title: 'Thekkady to Alleppey', description: 'Board your luxury houseboat. Cruise through backwater canals with freshly prepared Kerala meals onboard.', tags: ['Houseboat', 'Backwaters'] },
          { day: 6, title: 'Alleppey to Kovalam', description: 'Morning at Alleppey beach. Drive to Kovalam. Afternoon Ayurvedic spa session.', tags: ['Beach', 'Ayurveda'] },
          { day: 7, title: 'Departure', description: 'Leisure morning at Kovalam beach. Transfer to Trivandrum airport for departure.', tags: ['Departure'] },
        ],
        inclusions: ['Heritage & boutique hotel stays', 'Daily breakfast & select meals', 'Luxury houseboat (1 night)', 'Private car with driver', 'Ayurvedic spa session', 'All entry fees & permits', 'Kathakali show tickets'],
        exclusions: ['Flights to/from Kerala', 'Travel insurance', 'Personal expenses', 'Tips & gratuities', 'Lunch on non-houseboat days'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Coastal',
        rating: 4.8,
        reviewCount: 156,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Goa Beach Carnival',
        slug: 'goa-beach-carnival',
        destination: destMap['goa'],
        location: 'Goa, India',
        description: 'Sun-soaked beaches, vibrant nightlife, Portuguese colonial architecture, and delicious Goan cuisine. The perfect tropical beach holiday without leaving India.',
        duration: '5D/4N',
        days: 5,
        nights: 4,
        priceRange: { min: 12000, max: 30000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUUfCqgJ9Gbeyb42FOx7CdP978XZRHfyL8E0m5xpMYFLeOnAcuKhdXz5X-QYt41OeYf5ZTJexqqtSkCn770mDAFMOJt-HX2k4hkcA0qPFoLe80bOMfBz9c1RSFDQBAIat1VHsjDRzYhYosw008ZyhohnTgPA3QgnfiNBaE8g9tD04GUlIj4szjCv271iaYQG86jJ4_HWLXljKLNANNHHuLaJDx2FFmLM5Y5kOiad2U65YQD35dRmP6EYe5_2xaEt5h9Mv2sa_yNf2z',
        galleryImages: [],
        badge: 'Trending',
        tags: ['Beach', 'Nightlife', 'Heritage', 'Seafood', 'Water Sports'],
        highlights: [
          { icon: 'beach_access', title: 'Beach Hopping', description: 'Visit the best beaches — Baga, Calangute, Palolem, and hidden gems.' },
          { icon: 'nightlife', title: 'Nightlife', description: 'Experience Goa\'s legendary clubs, beach shacks, and moonlit parties.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Goa', description: 'Airport transfer. Check-in to beach resort. Evening at Baga Beach with sunset cocktails.', tags: ['Transfer', 'Beach'] },
          { day: 2, title: 'North Goa Explorer', description: 'Fort Aguada, Basilica of Bom Jesus, Fontainhas Latin Quarter walk. Evening at Tito\'s Lane.', tags: ['Heritage', 'Nightlife'] },
          { day: 3, title: 'Water Adventures', description: 'Full day water sports — parasailing, jet skiing, banana boat rides at Calangute. Spice plantation visit.', tags: ['Water Sports', 'Adventure'] },
          { day: 4, title: 'South Goa Serenity', description: 'Visit Palolem and Butterfly Beach. Traditional Goan fish curry lunch. Dudhsagar Falls excursion.', tags: ['Nature', 'Cuisine'] },
          { day: 5, title: 'Departure', description: 'Leisure morning. Local market shopping. Transfer to airport.', tags: ['Departure', 'Shopping'] },
        ],
        inclusions: ['Beach resort stay (4 nights)', 'Daily breakfast', 'Airport transfers', 'North & South Goa sightseeing', 'Water sports package', 'Spice plantation visit'],
        exclusions: ['Flights', 'Lunch & dinner', 'Nightlife expenses', 'Personal shopping', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Coastal',
        rating: 4.5,
        reviewCount: 234,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Himachal Hill Escape',
        slug: 'himachal-hill-escape',
        destination: destMap['himachal-pradesh'],
        location: 'Himachal Pradesh, India',
        description: 'From the colonial charm of Shimla to the adventure capital Manali, traverse through apple orchards, snow-capped peaks, and ancient temples in this Himalayan odyssey.',
        duration: '8D/7N',
        days: 8,
        nights: 7,
        priceRange: { min: 22000, max: 48000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAN0bl2w6UanVhpueRMK6iMr1IBW_Yeq2aQ2-EBatc9bvWf355qkKqRb8uHak6-U3-ClraHaNgBGWPSYx1qmtu_KoMCoPbyqDEVtjR3ITCm9XEp4fjbKGgxY53PwsEriTIijnb9ZSDYt7tqinwuHcptj-m9HgJJNpbzezDeE07XHoHoVZkx5UvnJkyloiAEuot1o2kVQnSfQRn6RjKZ-ZJ99jXwWhabJjDhM2neFD23046AOsHbIsweOXED8Qoxe2QlrHS0v3-eaFEy',
        galleryImages: [],
        badge: '',
        tags: ['Mountains', 'Snow', 'Adventure', 'Trekking', 'Scenic'],
        highlights: [
          { icon: 'terrain', title: 'Rohtang Pass', description: 'Drive to the breathtaking Rohtang Pass with panoramic Himalayan views.' },
          { icon: 'downhill_skiing', title: 'Snow Activities', description: 'Skiing, snowboarding, and snow tubing in Solang Valley.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Shimla', description: 'Arrive in Shimla. Check-in to heritage hotel. Evening stroll on Mall Road and Ridge.', tags: ['Transfer', 'Heritage'] },
          { day: 2, title: 'Shimla Sightseeing', description: 'Visit Jakhoo Temple, Christ Church, and Viceregal Lodge. Toy train ride to Kalka (optional).', tags: ['Sightseeing', 'Heritage'] },
          { day: 3, title: 'Shimla to Manali', description: 'Scenic drive through Kullu Valley. Stop at Pandoh Dam and Vaishno Devi Temple. Reach Manali by evening.', tags: ['Road Trip', 'Scenic'] },
          { day: 4, title: 'Manali Exploration', description: 'Hadimba Temple, Manu Temple, Old Manali. Evening at Van Vihar Park.', tags: ['Temple', 'Culture'] },
          { day: 5, title: 'Solang Valley Adventure', description: 'Full day at Solang Valley — paragliding, zorbing, and snow activities (seasonal).', tags: ['Adventure', 'Snow'] },
          { day: 6, title: 'Rohtang Pass Excursion', description: 'Drive to Rohtang Pass (subject to permits). Snow play and photography. Return to Manali.', tags: ['Snow', 'Photography'] },
          { day: 7, title: 'Manali to Dharamshala', description: 'Drive to Dharamshala. Visit Dalai Lama Temple Complex and Bhagsu Waterfall.', tags: ['Spiritual', 'Nature'] },
          { day: 8, title: 'Departure', description: 'Morning at McLeod Ganj market. Transfer to Gaggal airport or Pathankot station.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel stays (7 nights)', 'Daily breakfast', 'AC Volvo/Sedan transfers', 'Sightseeing as per itinerary', 'Rohtang Pass permit fees'],
        exclusions: ['Flights/trains', 'Adventure activity costs', 'Lunch & dinner', 'Personal expenses', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -25 },
          { tier: '4-Star', priceAdjustmentPercent: -12 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Mountain',
        rating: 4.7,
        reviewCount: 189,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Andaman Island Hopping',
        slug: 'andaman-island-hopping',
        destination: destMap['andaman-and-nicobar-islands'],
        location: 'Andaman & Nicobar, India',
        description: 'Dive into the turquoise waters of Havelock Island, explore the Cellular Jail\'s history, and discover pristine beaches that rival the Maldives — right within India.',
        duration: '6D/5N',
        days: 6,
        nights: 5,
        priceRange: { min: 30000, max: 60000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgU2JZLkDHJxrrhKi9py-SiyrOo27ZtVGYXzR0JYUopr1E3Ibpv3_qvlpYkUNdLstKmH2IXqhRuuAhW9ZjaHHy0g-34t4H_pup4Iq5F6CNTEiWFcc5vV7HUn3H7kNOgXbgrR59yu2uxBzLxD3SPXZzut2M2nGscaAKMUh-1DNZDEtyD3m12hauvZbVouA236xoMs4k2ItQykHouC7TYPPKh01MSI80ZxSnZle2ch1smW041LBFAd9-RTmn3tCXvsvupBK1rzJXTKeI',
        galleryImages: [],
        badge: 'New',
        tags: ['Island', 'Diving', 'Snorkeling', 'Beach', 'History'],
        highlights: [
          { icon: 'scuba_diving', title: 'Scuba Diving', description: 'Explore vibrant coral reefs with certified scuba diving sessions.' },
          { icon: 'beach_access', title: 'Radhanagar Beach', description: 'Named Asia\'s best beach — crystal-clear waters and powdery white sand.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Port Blair', description: 'Welcome at Veer Savarkar Airport. Visit Cellular Jail & attend Light and Sound show.', tags: ['Transfer', 'History'] },
          { day: 2, title: 'Port Blair to Havelock', description: 'Ferry to Havelock Island. Afternoon at Radhanagar Beach. Sunset photography.', tags: ['Ferry', 'Beach'] },
          { day: 3, title: 'Havelock Adventures', description: 'Morning scuba diving at Elephant Beach. Afternoon snorkeling and glass-bottom boat ride.', tags: ['Diving', 'Snorkeling'] },
          { day: 4, title: 'Havelock to Neil Island', description: 'Ferry to Neil Island. Visit Natural Bridge, Bharatpur Beach, and Laxmanpur sunset point.', tags: ['Ferry', 'Nature'] },
          { day: 5, title: 'Neil to Port Blair', description: 'Return ferry. Visit Ross Island and North Bay coral reef. Evening at Corbyn\'s Cove Beach.', tags: ['History', 'Coral Reef'] },
          { day: 6, title: 'Departure', description: 'Morning at leisure. Sagarika Emporium for souvenirs. Transfer to airport.', tags: ['Departure', 'Shopping'] },
        ],
        inclusions: ['Hotel & resort stays (5 nights)', 'Daily breakfast', 'Ferry tickets (all routes)', 'Scuba diving session', 'Snorkeling equipment', 'Cellular Jail entry & show', 'Airport & jetty transfers'],
        exclusions: ['Flights to/from Port Blair', 'Lunch & dinner', 'Extra water sports', 'Personal expenses', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -25 },
          { tier: '4-Star', priceAdjustmentPercent: -12 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Island',
        rating: 4.9,
        reviewCount: 98,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Royal Rajasthan',
        slug: 'royal-rajasthan',
        destination: destMap['rajasthan'],
        location: 'Rajasthan, India',
        description: 'Walk through the grandeur of India\'s royal heritage — from the Pink City of Jaipur to the Blue City of Jodhpur, golden sands of Jaisalmer, and the lakes of Udaipur.',
        duration: '9D/8N',
        days: 9,
        nights: 8,
        priceRange: { min: 35000, max: 70000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUD45bMtlYj3wamllJkxC1g1fATuM2HB5i8iRQ3Q615ywyjjwueCJIiB3jbmczY55KSc8wDPkVms-f0534L5eH1KnLAJWwqLrphsbuZQWyNlm8t6DpIOt6uykunN4HZpLG1p79lARv5bIJYI85bnI6AgtBXGUVJlvsvaNfrSZta3jZN7Oht1h-u_UJ9AyoQPpNepbui4bA-KltK348ejHE5rfVaXvcqruWehmWHAAq-vF4Nzcd0PKwENo0vGtHSJQQC31nQScZeQFi',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDCh4g2x_nB5uyF5SzkCeWGnOhwQOuHwHWtnOdftn1snyU1Tw9bG_ykdfo_AwEKr4yo7O2p872AONY_HX_HP2oUoR2xsoo6V6_8wA62SVCV1N2QBBzBQNf6NNzfyjE0x9vWsgUV7K72X3g_yZmCDuuk3ilPvRpxr1xXMJTb0r1YGvDrR6J2Qzpzw3cla-iTn0PoJ47l2l3btjXIQJlK2fPGo57Qe-AlLx8-xN5fJtKlmSi057aNGiUpKtPXfA4RZYQUsxcmkzeVudP5',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuCJnHlJIo1NLva6qGeqrSyS7sBqzcuqriz6L_AuqXUB9ihkW_ZPBIJny3NlK2UVoMB4hiqh59NLnTvkEixT2CObrWdHWzrS5AL8T6yDnwHjd7BBbozJd69xV7428bFngFWGijv1rnWz6UF4muZ3w2P4PKMQgDv2HC2kVoRSvwmkyYwGwgwlhCBSnREMNJ7LHkTEMKQ42Xk8bZx8fjFD_xlqnSptPHGsbUH4iKaaLTfcl1adFwwmbXJOsB-ki2YqZ9ehn2nBebfzXFD4',
        ],
        badge: 'Best Seller',
        tags: ['Heritage', 'Desert Safari', 'Palaces', 'Culture', 'Forts'],
        highlights: [
          { icon: 'palace', title: 'Royal Palaces', description: 'Visit the majestic forts and palaces of Jaipur, Udaipur, and Jodhpur.' },
          { icon: 'landscape', title: 'Desert Safari', description: 'Camel rides and overnight camping under the stars in the Thar Desert.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Jaipur', description: 'Welcome at Jaipur airport. Transfer to heritage hotel. Evening at leisure exploring local bazaars.', tags: ['Transfer', 'Welcome Dinner'] },
          { day: 2, title: 'The Pink City', description: 'Visit Amber Fort, City Palace, and Hawa Mahal. Traditional Rajasthani dinner with folk dance.', tags: ['Guided Tour', 'Heritage'] },
          { day: 3, title: 'Jaipur to Jodhpur', description: 'Drive to the Blue City. Explore Mehrangarh Fort and old city spice bazaars.', tags: ['Road Trip', 'Fort'] },
          { day: 4, title: 'Jodhpur to Jaisalmer', description: 'Drive to the Golden City. Evening walk around Jaisalmer Fort and Patwon ki Haveli.', tags: ['Road Trip', 'Heritage'] },
          { day: 5, title: 'Thar Desert Safari', description: 'Full-day desert experience: camel safari, sand dunes, and overnight camp with traditional dinner & music.', tags: ['Desert', 'Camping'] },
          { day: 6, title: 'Jaisalmer to Udaipur', description: 'Drive to the City of Lakes via Ranakpur Jain Temple. Evening boat ride on Lake Pichola.', tags: ['Road Trip', 'Lake'] },
          { day: 7, title: 'Udaipur Exploration', description: 'City Palace tour, Saheliyon ki Bari garden, and Jagdish Temple. Evening rooftop dinner overlooking the lake.', tags: ['Palace', 'Romantic'] },
          { day: 8, title: 'Udaipur Leisure', description: 'Optional excursion to Kumbhalgarh Fort or leisure day at hotel pool and spa.', tags: ['Leisure', 'Fort'] },
          { day: 9, title: 'Departure', description: 'Morning at leisure. Transfer to Udaipur airport.', tags: ['Departure'] },
        ],
        inclusions: ['Heritage hotel stays (8 nights)', 'Daily breakfast & select dinners', 'AC sedan with driver', 'Desert camp (1 night)', 'All monument entry fees', 'English-speaking guide', 'Camel safari', 'Boat ride on Lake Pichola'],
        exclusions: ['Flights', 'Travel insurance', 'Lunch', 'Personal expenses', 'Tips & gratuities'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Cultural',
        rating: 4.9,
        reviewCount: 214,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Uttarakhand Spiritual Trail',
        slug: 'uttarakhand-spiritual-trail',
        destination: destMap['uttarakhand'],
        location: 'Uttarakhand, India',
        description: 'From the spiritual Ganga Aarti in Rishikesh to thrilling river rafting, and from the serene Nainital lake to Jim Corbett\'s wildlife — Uttarakhand has it all.',
        duration: '6D/5N',
        days: 6,
        nights: 5,
        priceRange: { min: 15000, max: 35000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBykTSOcudF4tEZ5OkFbQShq3658sTZuytCERzqtKlOUwUr53cImMOU3IuCPpCZVFOFtBnq5vtMyNh2_v5vh1Lfzs8BFfR7mTY1hYobHbZnX7AOyZWyvANCKgfIVXGGk1JEaVKLz5l2ow1OCdlyqYJfyOuF2rq-hDvEOApjo5nLFeQL0vxofT4tCvLsBrpAjyqUyPFDcqTRLpOoqv8qHaop1VsYPKzgqZyLvYVb0_miplusG19f80ANZauJMrn81ZavkMi92dkurLz5',
        galleryImages: [],
        badge: '',
        tags: ['Spiritual', 'Rafting', 'Yoga', 'Wildlife', 'Adventure'],
        highlights: [
          { icon: 'kayaking', title: 'River Rafting', description: 'Grade III-IV white water rafting on the Ganges.' },
          { icon: 'self_improvement', title: 'Yoga & Meditation', description: 'Sunrise yoga sessions on the banks of the Ganges in Rishikesh.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Haridwar', description: 'Transfer to hotel. Evening Ganga Aarti at Har Ki Pauri ghat.', tags: ['Transfer', 'Spiritual'] },
          { day: 2, title: 'Haridwar to Rishikesh', description: 'Short drive to Rishikesh. Visit Beatles Ashram, Ram Jhula, Laxman Jhula. Evening yoga session.', tags: ['Spiritual', 'Yoga'] },
          { day: 3, title: 'Rishikesh Adventures', description: 'Morning white water rafting. Afternoon bungee jumping or cliff jump (optional). Café hopping.', tags: ['Rafting', 'Adventure'] },
          { day: 4, title: 'Rishikesh to Mussoorie', description: 'Drive to the Queen of Hills. Visit Kempty Falls, Gun Hill, and Mall Road.', tags: ['Hill Station', 'Scenic'] },
          { day: 5, title: 'Mussoorie to Dehradun', description: 'Lal Tibba viewpoint, Company Garden. Drive to Dehradun. Robber\'s Cave visit.', tags: ['Nature', 'Sightseeing'] },
          { day: 6, title: 'Departure', description: 'Transfer to Dehradun airport/railway station.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel stays (5 nights)', 'Daily breakfast', 'All transfers', 'River rafting', 'Ganga Aarti seating', 'Sightseeing tours'],
        exclusions: ['Flights/trains', 'Bungee & adventure extras', 'Lunch & dinner', 'Personal expenses'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -25 },
          { tier: '4-Star', priceAdjustmentPercent: -12 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Adventure',
        rating: 4.6,
        reviewCount: 145,
        isPopular: false,
        isFeatured: false,
      },
      {
        name: 'Kashmir Valley Dream',
        slug: 'kashmir-valley-dream',
        destination: destMap['jammu-and-kashmir'],
        location: 'Jammu & Kashmir, India',
        description: 'Experience the legendary beauty of Kashmir — shikara rides on Dal Lake, saffron fields of Pampore, the alpine meadows of Gulmarg, and the serenity of Pahalgam.',
        duration: '7D/6N',
        days: 7,
        nights: 6,
        priceRange: { min: 28000, max: 55000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWS1kF1W3NmmdC0E1TJZH7mz3wZQN4pazlT5zjr0Q_JLl9SgL9xqgbhHru2lyLke453Xiqythv7j1hMDnvXszY4DCT2DwDUCT9N6TxBCNzRV6TGo33fmAPRAfl_F7hKsD-4VQmDtrxdkNPMg7syezuqULWaF8RgSznadcctkToLFUvlj8J97y8aDdHT3UGXayjLQu99qy9pT3-YYDaZ0IpXVxX_a1ccpPdBw7ayyuPqV5AqTvFqFFLEUv_akoeb0B_jfRUFzPpeuWg',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuA4xbGOaKsxjN97ELeC0kt7iSmW9inE_a5IcBKwFzkMiEAJbE1IxAyELKMXX0HiwtgG32dH1ehGtSmUXfUhiy8T5jn55qf4bFJnr_n-jbXBkKpyV0X6_5BRGtCtmW7-EYcem-7ahJBhuM7kB83FlVVD9dp9qCtCNY5mD0_UCDIUQMaLGEXsl88NDb3E3Vde6EwYzMuQZOyqbCDoayNQRQWFty2SqtQyVkO7n6Z4HGzlzu9Cu7bR-3QD7Z4ht9BU-DXxfazQuYsOY3Sm',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuBeVMNubeyWnDFlQFw0ihqcpv-mNwURZAOPL_PhMTa2HY1Y6pOa3vTHD_QuKUPetVFX8-XHbU8MNBJtey5DWI-uFxt2OSENYQNuspDoTX66QQiFiYOlY9wjsUcDAJwPozdleoE5pcr_hfUyS2SpSyE_WAd5B11j_vM_SoqYsP62CUav3_ck2HHUjQ54NGDAPV64H_jFtjjUITDrYv2Ez366C7Bw9WsHy-KCWQF56A7qirESR6MJ9LQsslMSECaTSgVQJZbifN7GZMlX',
        ],
        badge: '',
        tags: ['Dal Lake', 'Shikara', 'Gondola', 'Meadows', 'Houseboat'],
        highlights: [
          { icon: 'sailing', title: 'Shikara Ride', description: 'Romantic shikara ride on the mirror-calm waters of Dal Lake.' },
          { icon: 'downhill_skiing', title: 'Gondola Ride', description: 'Asia\'s highest cable car ride in Gulmarg with Himalayan panorama.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Srinagar', description: 'Airport pickup. Check-in to luxury houseboat on Dal Lake. Evening shikara ride.', tags: ['Transfer', 'Houseboat'] },
          { day: 2, title: 'Srinagar Gardens', description: 'Visit Mughal Gardens — Nishat Bagh, Shalimar Bagh, and Chashme Shahi. Afternoon at local markets.', tags: ['Gardens', 'Heritage'] },
          { day: 3, title: 'Srinagar to Gulmarg', description: 'Drive to Gulmarg. Gondola ride to Kongdoori and Apharwat Peak. Snow activities.', tags: ['Gondola', 'Snow'] },
          { day: 4, title: 'Gulmarg to Pahalgam', description: 'Drive to the Valley of Shepherds. Visit Betaab Valley and Aru Valley.', tags: ['Meadows', 'Nature'] },
          { day: 5, title: 'Pahalgam Exploration', description: 'Pony ride to Baisaran meadow. Visit Lidder River for trout fishing.', tags: ['Pony Ride', 'River'] },
          { day: 6, title: 'Pahalgam to Srinagar', description: 'Return to Srinagar via saffron fields of Pampore. Evening free for shopping.', tags: ['Saffron', 'Shopping'] },
          { day: 7, title: 'Departure', description: 'Morning at leisure. Transfer to Srinagar airport.', tags: ['Departure'] },
        ],
        inclusions: ['Houseboat + hotel stays (6 nights)', 'Daily breakfast', 'Private car with driver', 'Gondola tickets', 'Shikara ride', 'Garden entry fees'],
        exclusions: ['Flights', 'Pony ride cost', 'Lunch & dinner', 'Snow activity charges', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Nature',
        rating: 4.8,
        reviewCount: 176,
        isPopular: true,
        isFeatured: false,
      },
      {
        name: 'Golden Triangle Heritage',
        slug: 'golden-triangle-heritage',
        destination: destMap['uttar-pradesh'],
        location: 'Delhi - Agra - Jaipur, India',
        description: 'India\'s most iconic circuit — the Taj Mahal at sunrise, Delhi\'s Mughal heritage, and Jaipur\'s pink-hued palaces. A perfect introduction to India\'s timeless grandeur.',
        duration: '5D/4N',
        days: 5,
        nights: 4,
        priceRange: { min: 18000, max: 40000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBNclNECedoflhi0cSxAK6iHlR7hRNLu-FP9Ds_Yo4LWCG5G3dy-XdbgfPsiPwmUJ9-MLn2ryHQv-nFMBRHMZcua6P0K3qVSO8hMhJyqOb9LivFh88WiJm0GO0novTC_QAvasT7k-L7wHuVvY-DQePmzJQZDNkgCTwACGRrPGgD6ZcOWhGoFrRUflw56-ktIXWdwGeJi4JpuPf4kKECa0UGB5bDNfcinhONm45HXpIjTBekK7aA_4Lb5y7pCRGojJtfgg-e11V53d1r',
        galleryImages: [],
        badge: '',
        tags: ['Taj Mahal', 'Heritage', 'Mughal', 'Culture', 'Golden Triangle'],
        highlights: [
          { icon: 'mosque', title: 'Taj Mahal Sunrise', description: 'Witness the Taj Mahal at dawn as it glows pink and gold.' },
          { icon: 'fort', title: 'Amber Fort', description: 'Explore the magnificent Amber Fort with elephant/jeep ride to the top.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Delhi', description: 'Airport pickup. Visit India Gate, Qutub Minar, and Humayun\'s Tomb. Evening at Chandni Chowk.', tags: ['Transfer', 'Heritage'] },
          { day: 2, title: 'Delhi to Agra', description: 'Drive to Agra. Afternoon visit Agra Fort. Sunset view of Taj from Mehtab Bagh.', tags: ['Road Trip', 'Fort'] },
          { day: 3, title: 'Taj Mahal & Agra to Jaipur', description: 'Sunrise Taj Mahal visit. Drive to Jaipur via Fatehpur Sikri ghost city.', tags: ['Taj Mahal', 'Heritage'] },
          { day: 4, title: 'Jaipur Exploration', description: 'Amber Fort, City Palace, Hawa Mahal, Jantar Mantar. Evening at Johari Bazaar.', tags: ['Forts', 'Shopping'] },
          { day: 5, title: 'Departure', description: 'Transfer to Jaipur airport or drive back to Delhi airport.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel stays (4 nights)', 'Daily breakfast', 'AC sedan', 'Monument entry fees', 'English-speaking guide at monuments'],
        exclusions: ['Flights', 'Meals other than breakfast', 'Camera fees at monuments', 'Personal expenses'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Heritage',
        rating: 4.7,
        reviewCount: 312,
        isPopular: true,
        isFeatured: false,
      },
      {
        name: 'Gujarat Cultural Explorer',
        slug: 'gujarat-cultural-explorer',
        destination: destMap['gujarat'],
        location: 'Gujarat, India',
        description: 'Discover the white desert of Kutch, the lions of Gir, sacred Somnath, and the vibrant handicraft traditions of Gujarat in this off-beat cultural journey.',
        duration: '7D/6N',
        days: 7,
        nights: 6,
        priceRange: { min: 20000, max: 42000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEEw_PPBqq94Smrm-zivW5LhkxtBdn-8Ivdd11jQOAZoFUvFkiiXK3m9wFSBFF3iiY27l08X_Sk7BvhOwZJdgwg1rRy7ankh1jJKrm-UHnORGrkJ3EC7JvCXH54S4fv8CQIyEoGPmS8ybQfWo1VmzoGCKABrlEVLQoKJwQbhMyTROYIXL8hHwJUEYf4qKxQ-ExVWeAdwgwCaGIv90sQJvk5maxhm_lerTmOl0N1vJTaG-qbdj4J1mgVfpEhbrFXhG1l1CV61jsWEq_',
        galleryImages: [],
        badge: '',
        tags: ['Rann of Kutch', 'Gir Lions', 'Temples', 'Handicrafts'],
        highlights: [
          { icon: 'landscape', title: 'White Rann', description: 'The surreal white salt desert under a full moon sky.' },
          { icon: 'pets', title: 'Gir Safari', description: 'Spot the endangered Asiatic lions in their natural habitat.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Ahmedabad', description: 'Airport pickup. Visit Sabarmati Ashram, Sidi Saiyyed Mosque, and Adalaj Stepwell.', tags: ['Transfer', 'Heritage'] },
          { day: 2, title: 'Ahmedabad to Kutch', description: 'Fly/drive to Bhuj. Visit Aina Mahal and the Kutch Museum. Handicraft shopping.', tags: ['Culture', 'Shopping'] },
          { day: 3, title: 'Rann of Kutch', description: 'Full day at the White Rann. Visit artisan villages. Evening cultural program at Rann Utsav tent city.', tags: ['Desert', 'Culture'] },
          { day: 4, title: 'Kutch to Gir', description: 'Drive/fly to Sasan Gir. Afternoon nature walk. Evening sunset at Somnath Temple.', tags: ['Travel', 'Temple'] },
          { day: 5, title: 'Gir Safari', description: 'Early morning jeep safari in Gir National Park. Spot Asiatic lions, leopards, and spotted deer.', tags: ['Safari', 'Wildlife'] },
          { day: 6, title: 'Gir to Dwarka', description: 'Drive to Dwarka. Visit Dwarkadhish Temple and Nageshwar Jyotirlinga.', tags: ['Spiritual', 'Temple'] },
          { day: 7, title: 'Departure', description: 'Transfer to Jamnagar airport.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel stays (6 nights)', 'Daily breakfast', 'All transfers', 'Gir safari jeep', 'Rann of Kutch entry', 'Guide services'],
        exclusions: ['Flights', 'Meals other than breakfast', 'Personal expenses', 'Camera fees'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -25 },
          { tier: '4-Star', priceAdjustmentPercent: -12 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Cultural',
        rating: 4.5,
        reviewCount: 89,
        isPopular: false,
        isFeatured: false,
      },
      {
        name: 'Lakshadweep Islands Retreat',
        slug: 'lakshadweep-islands-retreat',
        destination: destMap['lakshadweep'],
        location: 'Lakshadweep, India',
        description: 'India\'s own Maldives — explore the pristine lagoons, vibrant coral reefs, and untouched beaches of Agatti, Bangaram, and Kavaratti islands.',
        duration: '5D/4N',
        days: 5,
        nights: 4,
        priceRange: { min: 35000, max: 75000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5_nFiPFgg7uq1YpENSaveTpDPCTwOtYsC8wAhrS1cqCYGWuNzvsbo4m2piPD5QFiZcFaNPx16Sd-gMQq83kMlnEt5AaP_6knEQN9haPtbGM-3yrimZTMw8Po9lCPQXHd2BCs0a2ue-SFbwK_F01xBPpTszF2trrBfJ7ofMoLOickkK-8JyO40SkFs17bVrvbV1AcPQ_3KLw8aAPltet5VIQHcaF4FgwzjuunySZlgi1iVz2nA-swykz_6BIqBmE2fz0_FTLDMLOs1',
        galleryImages: [],
        badge: 'New',
        tags: ['Island', 'Coral', 'Lagoon', 'Snorkeling', 'Pristine'],
        highlights: [
          { icon: 'scuba_diving', title: 'Coral Reefs', description: 'Snorkel and dive through some of India\'s most vibrant coral ecosystems.' },
          { icon: 'kayaking', title: 'Kayaking', description: 'Glide through crystal-clear lagoons on a guided kayak tour.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Agatti', description: 'Flight from Kochi to Agatti. Boat transfer to Bangaram Island resort. Leisure evening.', tags: ['Flight', 'Island'] },
          { day: 2, title: 'Bangaram Exploration', description: 'Glass-bottom boat ride. Snorkeling in the lagoon. Beach BBQ lunch.', tags: ['Snorkeling', 'Beach'] },
          { day: 3, title: 'Kavaratti Island', description: 'Day trip to Kavaratti. Visit marine aquarium, mosque, and lagoon swim.', tags: ['Day Trip', 'Culture'] },
          { day: 4, title: 'Water Adventures', description: 'Scuba diving, deep-sea fishing, and kayaking. Sunset cruise around the atoll.', tags: ['Diving', 'Fishing'] },
          { day: 5, title: 'Departure', description: 'Morning at leisure. Boat to Agatti. Afternoon flight to Kochi.', tags: ['Departure'] },
        ],
        inclusions: ['Island resort stay (4 nights)', 'All meals', 'Boat transfers', 'Snorkeling gear', 'Glass-bottom boat ride', 'Island entry permits'],
        exclusions: ['Flights to/from Kochi-Agatti', 'Scuba diving (extra)', 'Personal expenses', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -20 },
          { tier: '4-Star', priceAdjustmentPercent: -10 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Island',
        rating: 4.7,
        reviewCount: 52,
        isPopular: false,
        isFeatured: false,
      },

      // ====== INTERNATIONAL PACKAGES ======
      {
        name: 'Bali & Beyond',
        slug: 'bali-and-beyond',
        destination: destMap['indonesia'],
        location: 'Bali, Indonesia',
        description: 'Rice terraces of Ubud, sacred monkey forests, ancient temples, volcanic sunrises, and the party beaches of Seminyak — Bali is a journey for the soul.',
        duration: '7D/6N',
        days: 7,
        nights: 6,
        priceRange: { min: 45000, max: 90000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHXBeHe4FJ6en28QVtjl52tU6d7r2I5YMBxwLPiCthycqSkI4nJBshj-vBDzpuYZPJJMGAEH3NNzL9bfkjCh2xdHJhEtWvqtp5INFexsoVSDoMmBQRHUP2I8wAX4RFVdcMIcLYyaAomIabsTGx8b_4WHRkIIz8epxh1pffFgYLZr8BBbJs7xZSFjS9giDG2CSxxP8yrPfJhJc3dNGGDWTD8W8KW58_bt2svwXyftzfKNLKy19kfzCsKWMoZCa2Bd5EubFZbvG5f6_B',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDISU6lJwFt3ggY7k_8H91ll0JdmgWKYefy0csvojSO2CF1MIyMT8eeoL4FwWNwJjsN5TvtFBGH6AUpvbGba2iSBep9H5sxvo9FlHpdff6B15s9tT1b0STdWXN5aMktDrZVbQm7jmZzGaJq2Xi1K84TJ1tWDJKb1pj5CKcluonNSWXVYkdzqwzoWotjbceZzC2AJnSOV0Bgk_67Dc0ybOl4jas6vNPrkMU_bMUr0vYjWAqQOSuOlSzAOxLe_Ez0af31pJWtsAqe6Fku',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuD83hi7VRPw1oot6fg-QZxfJ_OfkuOD7wUjhvuIXUxe_EWRxnKlbtgd72-lBkkaXZfinEussmuFSSuex6gGsSocMLs3d6XvTiMHGehbEXyeYxlTZQc6i_rt027YYTwz07saFGn6w8hSzhIBlNcFwG8kT04-9HE0mvtGRaXzm0VHCYjkgOSs-0IVN5ow-YXa2Sp6eP_F5MZ9TKQlnJG9wZ79AVN-SV1z1BdZ9Vwds5R0GD_ut4926g8B0cphK7U23rJNG6ggUHAqzJAa',
        ],
        badge: 'Trending',
        tags: ['Temples', 'Rice Terraces', 'Surfing', 'Culture', 'Beach'],
        highlights: [
          { icon: 'temple_buddhist', title: 'Sacred Temples', description: 'Visit Tanah Lot sea temple and Uluwatu cliffside temple at sunset.' },
          { icon: 'landscape', title: 'Tegallalang Terraces', description: 'Walk through the iconic UNESCO rice terraces of Ubud.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Bali', description: 'Airport pickup. Transfer to Seminyak beach hotel. Sunset at Seminyak Beach.', tags: ['Transfer', 'Beach'] },
          { day: 2, title: 'Ubud Cultural Day', description: 'Tegallalang rice terraces, Tirta Empul water temple, monkey forest. Art market shopping.', tags: ['Culture', 'Nature'] },
          { day: 3, title: 'Mount Batur Sunrise', description: 'Pre-dawn trek to Mount Batur for volcanic sunrise. Natural hot springs. Afternoon rest.', tags: ['Trekking', 'Volcano'] },
          { day: 4, title: 'Nusa Penida Day Trip', description: 'Speed boat to Nusa Penida. Kelingking Beach, Angel\'s Billabong, Broken Beach.', tags: ['Island', 'Beach'] },
          { day: 5, title: 'Uluwatu & Beaches', description: 'Visit Uluwatu Temple. Kecak fire dance at sunset. Dinner at Jimbaran seafood bay.', tags: ['Temple', 'Dance'] },
          { day: 6, title: 'Water Sports & Leisure', description: 'Surfing lesson at Kuta Beach. Afternoon spa treatment. Evening Seminyak nightlife.', tags: ['Surfing', 'Spa'] },
          { day: 7, title: 'Departure', description: 'Morning at leisure. Transfer to airport.', tags: ['Departure'] },
        ],
        inclusions: ['Resort stays (6 nights)', 'Daily breakfast', 'Airport transfers', 'Nusa Penida day trip', 'Mt. Batur trek guide', 'Uluwatu dance tickets'],
        exclusions: ['International flights', 'Visa on arrival', 'Lunch & dinner', 'Surfing lesson', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Cultural',
        rating: 4.8,
        reviewCount: 198,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Thailand Explorer',
        slug: 'thailand-explorer',
        destination: destMap['thailand'],
        location: 'Bangkok - Phuket - Krabi, Thailand',
        description: 'From Bangkok\'s glittering temples and floating markets to Phuket\'s party beaches and Krabi\'s limestone karst islands — the ultimate Thai experience.',
        duration: '8D/7N',
        days: 8,
        nights: 7,
        priceRange: { min: 40000, max: 80000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4xbGOaKsxjN97ELeC0kt7iSmW9inE_a5IcBKwFzkMiEAJbE1IxAyELKMXX0HiwtgG32dH1ehGtSmUXfUhiy8T5jn55qf4bFJnr_n-jbXBkKpyV0X6_5BRGtCtmW7-EYcem-7ahJBhuM7kB83FlVVD9dp9qCtCNY5mD0_UCDIUQMaLGEXsl88NDb3E3Vde6EwYzMuQZOyqbCDoayNQRQWFty2SqtQyVkO7n6Z4HGzlzu9Cu7bR-3QD7Z4ht9BU-DXxfazQuYsOY3Sm',
        galleryImages: [],
        badge: 'Best Seller',
        tags: ['Temples', 'Islands', 'Street Food', 'Nightlife', 'Beach'],
        highlights: [
          { icon: 'temple_buddhist', title: 'Grand Palace', description: 'Visit Bangkok\'s magnificent Grand Palace and Wat Phra Kaew.' },
          { icon: 'kayaking', title: 'Phi Phi Islands', description: 'Full-day boat tour to the stunning Phi Phi Islands and Maya Bay.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Bangkok', description: 'Airport pickup. Evening Chao Phraya dinner cruise.', tags: ['Transfer', 'Cruise'] },
          { day: 2, title: 'Bangkok Temples', description: 'Grand Palace, Wat Pho, Wat Arun. Afternoon at Chatuchak market.', tags: ['Temple', 'Shopping'] },
          { day: 3, title: 'Floating Markets', description: 'Damnoen Saduak floating market. Maeklong railway market. Evening at Khao San Road.', tags: ['Market', 'Culture'] },
          { day: 4, title: 'Bangkok to Phuket', description: 'Fly to Phuket. Check-in to beach resort. Evening at Patong Beach.', tags: ['Flight', 'Beach'] },
          { day: 5, title: 'Phi Phi Islands', description: 'Full-day speedboat tour to Phi Phi Islands. Snorkeling at Maya Bay. Beach BBQ.', tags: ['Island', 'Snorkeling'] },
          { day: 6, title: 'Phuket to Krabi', description: 'Ferry to Krabi. Railay Beach visit. Rock climbing or kayaking.', tags: ['Ferry', 'Adventure'] },
          { day: 7, title: 'Four Islands Tour', description: 'Boat tour to Tup, Chicken, Poda islands and Phra Nang beach. Evening at Ao Nang.', tags: ['Islands', 'Beach'] },
          { day: 8, title: 'Departure', description: 'Transfer to Krabi airport.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel/resort stays (7 nights)', 'Daily breakfast', 'Domestic flights', 'Phi Phi island tour', 'Four islands tour', 'All transfers'],
        exclusions: ['International flights', 'Visa fees', 'Lunch & dinner', 'Travel insurance', 'Optional activities'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Adventure',
        rating: 4.7,
        reviewCount: 267,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Singapore City Break',
        slug: 'singapore-city-break',
        destination: destMap['singapore'],
        location: 'Singapore',
        description: 'A compact yet extraordinary city-state — Gardens by the Bay\'s supertrees, Marina Bay Sands infinity pool, Sentosa Island thrills, and some of Asia\'s best street food.',
        duration: '5D/4N',
        days: 5,
        nights: 4,
        priceRange: { min: 55000, max: 110000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBeVMNubeyWnDFlQFw0ihqcpv-mNwURZAOPL_PhMTa2HY1Y6pOa3vTHD_QuKUPetVFX8-XHbU8MNBJtey5DWI-uFxt2OSENYQNuspDoTX66QQiFiYOlY9wjsUcDAJwPozdleoE5pcr_hfUyS2SpSyE_WAd5B11j_vM_SoqYsP62CUav3_ck2HHUjQ54NGDAPV64H_jFtjjUITDrYv2Ez366C7Bw9WsHy-KCWQF56A7qirESR6MJ9LQsslMSECaTSgVQJZbifN7GZMlX',
        galleryImages: [],
        badge: '',
        tags: ['City', 'Shopping', 'Food', 'Gardens', 'Universal Studios'],
        highlights: [
          { icon: 'park', title: 'Gardens by the Bay', description: 'Marvel at the iconic Supertree Grove and Cloud Forest dome.' },
          { icon: 'attractions', title: 'Sentosa Island', description: 'Universal Studios, S.E.A. Aquarium, and adventure cove waterpark.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Singapore', description: 'Changi Airport pickup. Marina Bay Sands area walk. Gardens by the Bay light show.', tags: ['Transfer', 'City'] },
          { day: 2, title: 'City Highlights', description: 'Merlion Park, Chinatown, Little India, and Haji Lane. Evening Clarke Quay dinner.', tags: ['Culture', 'Food'] },
          { day: 3, title: 'Sentosa Island', description: 'Full day at Universal Studios Singapore. Evening Wings of Time show.', tags: ['Theme Park', 'Entertainment'] },
          { day: 4, title: 'Nature & Shopping', description: 'Singapore Zoo morning visit. Afternoon at Orchard Road shopping. Night Safari.', tags: ['Wildlife', 'Shopping'] },
          { day: 5, title: 'Departure', description: 'Jewel Changi exploration. Transfer to airport.', tags: ['Departure', 'Shopping'] },
        ],
        inclusions: ['Hotel stays (4 nights)', 'Daily breakfast', 'Airport transfers', 'Gardens by the Bay tickets', 'Universal Studios pass', 'Singapore Zoo + Night Safari'],
        exclusions: ['International flights', 'Visa', 'Meals beyond breakfast', 'Shopping', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Urban',
        rating: 4.6,
        reviewCount: 143,
        isPopular: false,
        isFeatured: false,
      },
      {
        name: 'Malaysia Adventure',
        slug: 'malaysia-adventure',
        destination: destMap['malaysia'],
        location: 'Kuala Lumpur - Langkawi, Malaysia',
        description: 'From the gleaming Petronas Towers to the turquoise waters of Langkawi, experience Malaysia\'s perfect blend of city sophistication and tropical island bliss.',
        duration: '6D/5N',
        days: 6,
        nights: 5,
        priceRange: { min: 40000, max: 80000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrvoxh0MxPnPiDgE5B52XG-Pie4-XbuwjKoWXmuFrmdMYxtCQ2pIIRL1u7RG4UadeTMdY02j_eHF-gYLpwuSKYibs8RvEfDdMkQoq6blKET3fqaU32Y0_5GUdrrWOtaQeKsMzG_rBu6zJpOKg5m293kCzo2sybyS-28JtjsZFxKF9ow8BKmSI1eu2maTMki6g1KaDZRxz88mLWp4ssvJ_Xh7fYsWXxLs-pZP4w267S9IlodkwZ5Lr8h_j3E3w4A7vcyggJI43WLV4K',
        galleryImages: [],
        badge: '',
        tags: ['Twin Towers', 'Islands', 'Cable Car', 'Mangroves', 'Duty Free'],
        highlights: [
          { icon: 'location_city', title: 'Petronas Towers', description: 'Visit the world-famous Petronas Twin Towers sky bridge.' },
          { icon: 'forest', title: 'Langkawi Sky Bridge', description: 'Cable car ride to the iconic sky bridge with panoramic views.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in KL', description: 'Airport pickup. Petronas Towers visit. Evening at Jalan Alor street food market.', tags: ['Transfer', 'City'] },
          { day: 2, title: 'KL Heritage Trail', description: 'Batu Caves, KL Tower, Central Market. Evening at Bukit Bintang.', tags: ['Culture', 'Shopping'] },
          { day: 3, title: 'KL to Langkawi', description: 'Fly to Langkawi. Check-in to beach resort. Pantai Cenang beach evening.', tags: ['Flight', 'Beach'] },
          { day: 4, title: 'Langkawi Island Hopping', description: 'Boat tour to Dayang Bunting Lake, Singa Besar Island, and Beras Basah Island.', tags: ['Island', 'Nature'] },
          { day: 5, title: 'Sky Bridge & Mangroves', description: 'Cable car to Sky Bridge. Mangrove kayak tour. Eagle watching. Duty-free shopping.', tags: ['Adventure', 'Shopping'] },
          { day: 6, title: 'Departure', description: 'Morning leisure. Transfer to Langkawi airport.', tags: ['Departure'] },
        ],
        inclusions: ['Hotel/resort stays (5 nights)', 'Daily breakfast', 'Domestic flights', 'Island hopping tour', 'Cable car tickets', 'All transfers'],
        exclusions: ['International flights', 'Visa', 'Lunch & dinner', 'Optional activities', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -25 },
          { tier: '4-Star', priceAdjustmentPercent: -12 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Nature',
        rating: 4.5,
        reviewCount: 112,
        isPopular: false,
        isFeatured: false,
      },
      {
        name: 'Maldives Luxury Escape',
        slug: 'maldives-luxury-escape',
        destination: destMap['maldives'],
        location: 'Maldives, Indian Ocean',
        description: 'The ultimate luxury getaway — overwater villas, private yacht expeditions, world-class diving, and the most pristine coral reefs on the planet.',
        duration: '6D/5N',
        days: 6,
        nights: 5,
        priceRange: { min: 120000, max: 280000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhQKeAaOwLL4QET6WPo7YZ8jF0e2VsSzyLal3aM8Yin8dYJrJcHJ_H1uOa05mzSX_otZ8bjZ3Rv5Cpb1kv3iE8YKXoUudRc7m30Fj2E66ynWtX6IgXDMOblfHQuM903t3dn_8MalFDuu-GuZ4WYci8XsXdaeFNIjbxYdefMS0CWUZSBdX5hy5YqzdZ0E3iKaZIzbjD32QYoYOrUaG_mDcnMlBkcjVS1fTPX_KpcjqFPbklDPgHVIYW0vPbMgMPJHpSEzUXqb3pSm8P',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuC1LbVlKYjedrexvv4vFLE_YRFVhf22_e_7GES-iFS2oliAm1-vxo86vr0aDs_2334rw0QnygORt9R-pjkT0ETejS5oUoVx-SdX0lqjrxvye4A8zJ2BS_TpOXkb7T-AlgegN4tOJz2ZbSE3YVxJJ6TM-wvJjbg8tnNpmq7gq5UY8CM193a_5gJcI-VnJzf75MKtkxgdsLQ-U66vGg_wPbOjcvFnx12zAVDTR6AQeSjQu4vNSe7rnx-dSUnczYFOKmwXjAsA_a5QKq4P',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDgU2JZLkDHJxrrhKi9py-SiyrOo27ZtVGYXzR0JYUopr1E3Ibpv3_qvlpYkUNdLstKmH2IXqhRuuAhW9ZjaHHy0g-34t4H_pup4Iq5F6CNTEiWFcc5vV7HUn3H7kNOgXbgrR59yu2uxBzLxD3SPXZzut2M2nGscaAKMUh-1DNZDEtyD3m12hauvZbVouA236xoMs4k2ItQykHouC7TYPPKh01MSI80ZxSnZle2ch1smW041LBFAd9-RTmn3tCXvsvupBK1rzJXTKeI',
        ],
        badge: '',
        tags: ['Luxury', 'Overwater Villa', 'Diving', 'Honeymoon', 'Spa'],
        highlights: [
          { icon: 'sailing', title: 'Private Yacht', description: 'Full-day private yacht expedition to secluded atolls and sandbanks.' },
          { icon: 'scuba_diving', title: 'World-Class Diving', description: 'Guided dive trips to manta ray points and vibrant coral gardens.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Malé', description: 'Seaplane transfer to resort island. Check-in to overwater villa. Sunset cocktails on deck.', tags: ['Seaplane', 'Welcome'] },
          { day: 2, title: 'Underwater World', description: 'Morning guided snorkeling safari. Afternoon scuba diving session. Underwater dining experience.', tags: ['Diving', 'Snorkeling'] },
          { day: 3, title: 'Yacht Expedition', description: 'Private yacht cruise to sandbank. Dolphin watching. Fishing trip with chef cook-your-catch dinner.', tags: ['Yacht', 'Dolphin'] },
          { day: 4, title: 'Island Wellness', description: 'Overwater spa treatment. Yoga session at sunrise. Island hopping to local village.', tags: ['Spa', 'Yoga'] },
          { day: 5, title: 'Adventure Day', description: 'Water sports — jet ski, parasailing, kayaking. Night snorkeling with manta rays.', tags: ['Water Sports', 'Adventure'] },
          { day: 6, title: 'Departure', description: 'Sunrise from villa. Seaplane back to Malé. International flight connection.', tags: ['Departure'] },
        ],
        inclusions: ['Overwater villa (5 nights)', 'All meals (full board)', 'Seaplane transfers', 'Private yacht day', '2 guided dives', 'Spa treatment', 'Water sports package'],
        exclusions: ['International flights', 'Travel insurance', 'Premium spirits', 'Specialty dive equipment'],
        hotelStandards: [
          { tier: '4-Star', priceAdjustmentPercent: -20 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Island',
        rating: 4.9,
        reviewCount: 87,
        isPopular: true,
        isFeatured: true,
      },
      {
        name: 'Dubai Extravaganza',
        slug: 'dubai-extravaganza',
        destination: destMap['dubai'],
        location: 'Dubai, UAE',
        description: 'Soar above the clouds at Burj Khalifa, shop at The Dubai Mall, ride dunes in the desert, and cruise the glittering Marina — Dubai delivers non-stop luxury and adventure.',
        duration: '6D/5N',
        days: 6,
        nights: 5,
        priceRange: { min: 60000, max: 130000, currency: '₹' },
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD83hi7VRPw1oot6fg-QZxfJ_OfkuOD7wUjhvuIXUxe_EWRxnKlbtgd72-lBkkaXZfinEussmuFSSuex6gGsSocMLs3d6XvTiMHGehbEXyeYxlTZQc6i_rt027YYTwz07saFGn6w8hSzhIBlNcFwG8kT04-9HE0mvtGRaXzm0VHCYjkgOSs-0IVN5ow-YXa2Sp6eP_F5MZ9TKQlnJG9wZ79AVN-SV1z1BdZ9Vwds5R0GD_ut4926g8B0cphK7U23rJNG6ggUHAqzJAa',
        galleryImages: [
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDrvoxh0MxPnPiDgE5B52XG-Pie4-XbuwjKoWXmuFrmdMYxtCQ2pIIRL1u7RG4UadeTMdY02j_eHF-gYLpwuSKYibs8RvEfDdMkQoq6blKET3fqaU32Y0_5GUdrrWOtaQeKsMzG_rBu6zJpOKg5m293kCzo2sybyS-28JtjsZFxKF9ow8BKmSI1eu2maTMki6g1KaDZRxz88mLWp4ssvJ_Xh7fYsWXxLs-pZP4w267S9IlodkwZ5Lr8h_j3E3w4A7vcyggJI43WLV4K',
          'https://lh3.googleusercontent.com/aida-public/AB6AXuCHXBeHe4FJ6en28QVtjl52tU6d7r2I5YMBxwLPiCthycqSkI4nJBshj-vBDzpuYZPJJMGAEH3NNzL9bfkjCh2xdHJhEtWvqtp5INFexsoVSDoMmBQRHUP2I8wAX4RFVdcMIcLYyaAomIabsTGx8b_4WHRkIIz8epxh1pffFgYLZr8BBbJs7xZSFjS9giDG2CSxxP8yrPfJhJc3dNGGDWTD8W8KW58_bt2svwXyftzfKNLKy19kfzCsKWMoZCa2Bd5EubFZbvG5f6_B',
        ],
        badge: 'Trending',
        tags: ['Luxury', 'Burj Khalifa', 'Desert Safari', 'Shopping', 'Marina'],
        highlights: [
          { icon: 'apartment', title: 'Burj Khalifa', description: 'Visit the world\'s tallest building observation deck at 148th floor.' },
          { icon: 'landscape', title: 'Desert Safari', description: 'Evening dune bashing, camel ride, BBQ dinner, and belly dance show.' },
        ],
        itinerary: [
          { day: 1, title: 'Arrival in Dubai', description: 'Airport pickup. Check-in to hotel. Evening at Dubai Marina & JBR Beach Walk.', tags: ['Transfer', 'Marina'] },
          { day: 2, title: 'Dubai City Tour', description: 'Burj Khalifa "At The Top", Dubai Mall, Dubai Fountain show. Old Dubai creek & souks.', tags: ['Sightseeing', 'Shopping'] },
          { day: 3, title: 'Desert Safari', description: 'Morning at leisure. Afternoon desert safari — dune bashing, camel riding, BBQ dinner, belly dance.', tags: ['Desert', 'Adventure'] },
          { day: 4, title: 'Abu Dhabi Day Trip', description: 'Visit Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, and Yas Island. Return to Dubai.', tags: ['Day Trip', 'Culture'] },
          { day: 5, title: 'Theme Parks & Leisure', description: 'Visit Dubai Frame or Miracle Garden. Afternoon Atlantis Aquaventure or Dubai Parks.', tags: ['Theme Park', 'Leisure'] },
          { day: 6, title: 'Departure', description: 'Last-minute shopping at Dubai Mall. Transfer to DXB airport.', tags: ['Departure', 'Shopping'] },
        ],
        inclusions: ['Hotel stays (5 nights)', 'Daily breakfast', 'Airport transfers', 'Burj Khalifa tickets', 'Desert safari with dinner', 'Abu Dhabi day trip', 'Dhow cruise dinner'],
        exclusions: ['International flights', 'Visa', 'Lunch', 'Theme park tickets', 'Shopping', 'Travel insurance'],
        hotelStandards: [
          { tier: '3-Star', priceAdjustmentPercent: -30 },
          { tier: '4-Star', priceAdjustmentPercent: -15 },
          { tier: '5-Star Elite', priceAdjustmentPercent: 0 },
        ],
        type: 'Urban',
        rating: 4.7,
        reviewCount: 203,
        isPopular: true,
        isFeatured: true,
      },
    ];

    const createdPackages = await Package.insertMany(packages);
    console.log(`✅ Created ${createdPackages.length} packages`);

    // Create testimonials
    const testimonials = [
      {
        name: 'Priya Sharma',
        location: 'Traveler from Mumbai',
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9oesH0vsVn-VKaJcdeGdVyBZ0pvedrq82fGKGpAhplUM_XtrEosGFN5gdOmwkScCpQvL8goGCUTYS7j9Np8g5frwqGn-tVf0u9AE-6GS4l1DHdK8GA0ah1tNkzNiUwlnNyffWD_d5G_XGxL-df1hH5XM-w59zMOl7-Ws-Gfqcu_uOZRWewbPt-1gXnlQaoeKmKg1YlNweH22fIN2gRzXys8pLbMXur90ovF-XPRe_G2PGXMWWqKn_p8joknyAFxohKp3P7uaDXqDQ',
        quote: 'Our Kerala houseboat experience was nothing short of magical. The backwaters at sunset, the freshly prepared Kerala meals onboard, and the Ayurvedic spa — every moment was curated to perfection. Infinity Miles truly made our honeymoon unforgettable.',
        rating: 5,
        travelDate: 'December 2024',
        destination: destMap['kerala'],
      },
      {
        name: 'Rahul Verma',
        location: 'Explorer from Delhi',
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcDbwWDImIIZ9sMJ9xpkbFZnEt0XnzwK00D2c-wg0y4PIg2KgI-vY3E6oWZEJz_FxvERpeQhfiyp52ULwpTVJBTp9pDHcjWrahnJ2uj_gpPlloyUPZUZld-gR7zvl1e6zrT_KHkRBAWOu901BCap1vM0KGWJQgVTASXNw47mHwAve_A4pdHrAmFxo_PBjK-Fl36tajU623kCId-bViYVo9G-HOskhMZHkYz3ZmzhAflssLn8nFZQiue8KTHwYIRvWIqvzXYcIgRGtj',
        quote: 'The Royal Rajasthan package exceeded every expectation. Sleeping under the stars in the Thar Desert, the heritage palace hotels, and the warmth of Rajasthani hospitality — absolutely worth every rupee!',
        rating: 4.5,
        travelDate: 'November 2024',
        destination: destMap['rajasthan'],
      },
      {
        name: 'Ananya Nair',
        location: 'Wanderlust from Bangalore',
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8cRa0xnIINO_rz4t7IDYYZvdqUC5DQ-ZylUIDBS_JSkNARE9geP8TIh8Z2yXGAlsGd8-M3fRYEF3mjbkdu6rJHcL-26TEW_gnAQ7KtgoigCoagNXkJupeuw6tpLzubsYL9DNW3gVD4QZOHPTKGiASjmam4U79NrD1s6eEmhry40zKtMwcXMtGeOxbvBHfNYYcIxdXKzs_dt7d9IJ7IWaAPxNTF2Hw4OtIpSB81J36TS5PY5VPX0sVXjsuQEZjaiHIglOEmKH8BwMO',
        quote: 'Bali was a dream come true. The sunrise trek to Mount Batur was the highlight — watching the sun rise above the clouds was a life-changing moment. The team\'s planning was impeccable throughout.',
        rating: 5,
        travelDate: 'January 2025',
        destination: destMap['indonesia'],
      },
    ];

    const createdTestimonials = await Testimonial.insertMany(testimonials);
    console.log(`✅ Created ${createdTestimonials.length} testimonials`);

    // Create default admin user (only if none exists)
    const existingAdmin = await AdminUser.findOne({ role: 'admin' });
    if (!existingAdmin) {
      await AdminUser.create({
        username: 'admin',
        email: 'admin@infinitymiles.com',
        password: 'admin123',
        role: 'admin',
      });
      console.log('✅ Created default admin user (username: admin, password: admin123)');
    }

    console.log('\n🎉 Seed completed successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
}

seed();
